# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: lib/service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'lib/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11lib/service.proto\"\"\n\x0c\x46rameRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\")\n\rFrameResponse\x12\x18\n\x10response_message\x18\x01 \x01(\t2G\n\x16ImageProcessingService\x12-\n\x0cProcessFrame\x12\r.FrameRequest\x1a\x0e.FrameResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lib.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=21
  _globals['_FRAMEREQUEST']._serialized_end=55
  _globals['_FRAMERESPONSE']._serialized_start=57
  _globals['_FRAMERESPONSE']._serialized_end=98
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_start=100
  _globals['_IMAGEPROCESSINGSERVICE']._serialized_end=171
# @@protoc_insertion_point(module_scope)
